version: "3"
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    links:
      - alertmanager:alertmanager
    restart: always
    deploy:
      mode: global
    ports:
      - 9090:9090
    depends_on:
      - go-service-with-metrics
  node-exporter:
    image: prom/node-exporter
    command:
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    restart: always
    deploy:
      mode: global

  go-service-with-metrics:
    build: .
    ports:
      - 8080:8080

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    depends_on:
      - prometheus
  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - ./alertmanager:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/etc/alertmanager/data'
    ports:
      - 9093:9093
  pushgateway:
    image: prom/pushgateway:latest
    ports:
      - 9091:9091
    depends_on:
      - prometheus
  telegram-alertmanager-bot:
    image: moghaddas/prometheus_bot
    volumes:
      - ./telegram:/etc/telegram/
    command:
      - '-c=/etc/telegram/config.yml'
    ports:
      - 9087:9087
    depends_on:
      - alertmanager