groups:
- name: AllInstances
  rules:
  - alert: InstanceDown
    # Condition for alerting
    expr: up == 0
    for: 1m
    # Annotation - additional informational labels to store more information
    annotations:
      title: 'Instance {{ $labels.instance }} down'
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'
    # Labels - additional labels to be attached to the alert
    labels:
      severity: 'critical'
- name: Test Alert
  rules:
  - alert: Test Alert
    # Condition for alerting
    expr: operation_total{path="/alert"} > 0
    # Annotation - additional informational labels to store more information
    annotations:
      title: 'Test Alert Title'
      description: 'Test Alert description'
    # Labels - additional labels to be attached to the alert
    labels:
      severity: 'critical'