route:
  receiver: 'telegram'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  group_by: [cluster, alertname]


  routes:
    - receiver: 'telegram'
      group_wait: 10s
      match_re:
        alertname: ".*"
      continue: true

receivers:
  - name: 'telegram'
    webhook_configs:
    - send_resolved: True
      url: http://telegram-alertmanager-bot:9087/alert/808512577